version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  php-composer-phpunit:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd php-composer-phpunit && make docker
  javascript-axios:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd javascript-axios && make docker
  javascript-jest-puppeteer:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd javascript-jest-puppeteer && make test
  java-serenity-jbehave:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd java-serenity-jbehave && make test
  java-maven-junit4:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd java-maven-junit4 && make test
  java-maven-selenium:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd java-maven-selenium && make test
  javascript-cypress-js:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd javascript-cypress-js && make test
  javascript-webdriver-io:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd javascript-webdriver-io && make test
  ruby-rspec:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd ruby-rspec && make docker
  ruby-cucumber-test:
    machine: true
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd ruby-cucumber-test && make docker
  python2-pytest:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd python2-pytest && make test
  python3-robotframework:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd python3-robotframework && make test
  golang:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: echo "API_KEY=$API_KEY" > .env
      - run: cd golang-email-test && make test
  csharp-dotnet-core2-selenium:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: |
          $ErrorActionPreference = "Stop";
          choco install firefox;
          choco install selenium-gecko-driver;
          cd csharp-dotnet-core2-selenium;
          dotnet.exe restore;
          dotnet.exe test;
          exit
  csharp-dotnet-core3:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: |
          cd csharp-dotnet-core3
          dotnet restore
          dotnet build
          dotnet test

workflows:
  version: 2
  test:
    jobs:
      - php-composer-phpunit
      - javascript-axios
      - javascript-jest-puppeteer
      - javascript-cypress-js
      - javascript-webdriver-io
      - ruby-cucumber-test
      - ruby-rspec
      - python2-pytest
      - python3-robotframework
      - golang
      - java-maven-junit4
      - java-maven-selenium
      - java-serenity-jbehave
      - csharp-dotnet-core2-selenium
      - csharp-dotnet-core3
