name: dart_email_testing
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.5
  mailslurp: ^11.6.15
