name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup ci
        run: API_KEY=${{ secrets.API_KEY }} make ci-env
      - name: Run Javascript examples
        run: |
          for f in ./javascript*
          do
            echo "Run $f tests"
            cd "$f"
            make test
            cd -
          done

